language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g appcenter-cli
  - appcenter login --token $APPCENTER_TOKEN
  - chmod +x release-android-bundle.sh
script:
  - yarn install
  - ./release-android-bundle.sh
branches:
  only:
  - master
